use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use rusqlite::{functions::FunctionFlags, Connection};
use serde_json::json;
use tempfile::tempdir;

use ctx_history_core::{database_path, CaptureProvider};
use ctx_history_store::Store;

use super::rederive::{self, RebuildOutcome};
use super::*;
use crate::analytics::{ImportTelemetry, ProviderRefreshTrigger};
use crate::commands::import::{run_import_internal, ImportRunOptions, ProviderRefreshCollector};
use crate::config::AppConfig;
use crate::output::JsonOutputFormat;
use crate::progress::ProgressArg;
use crate::provider_sources::explicit_path_source;
use crate::ImportArgs;

fn line(value: serde_json::Value) -> String {
    format!("{value}\n")
}

fn codex_session(session_id: &str, turns: usize) -> String {
    let mut text = line(json!({
        "timestamp": "2026-07-27T00:00:00Z",
        "type": "session_meta",
        "payload": {
            "id": session_id,
            "timestamp": "2026-07-27T00:00:00Z",
            "cwd": "/workspace",
            "source": "cli"
        }
    }));
    for turn in 0..turns {
        text.push_str(&line(json!({
            "timestamp": "2026-07-27T00:00:01Z",
            "type": "response_item",
            "payload": {
                "type": "message",
                "role": "user",
                "content": [{
                    "type": "input_text",
                    "text": format!("provider projection turn {turn} in {session_id}")
                }]
            }
        })));
    }
    text
}

fn corpus(root: &Path) -> PathBuf {
    let sessions = root.join("sessions");
    fs::create_dir_all(&sessions).unwrap();
    for (index, session_id) in [
        "019f5a54-67de-7422-9841-e9872df75f44",
        "019f5a54-67de-7422-9841-e9872df75f45",
    ]
    .into_iter()
    .enumerate()
    {
        fs::write(
            sessions.join(format!(
                "rollout-2026-07-27T00-00-0{index}-{session_id}.jsonl"
            )),
            codex_session(session_id, 4 + index),
        )
        .unwrap();
    }
    sessions
}

fn import_args(path: &Path) -> ImportArgs {
    ImportArgs {
        provider: Some(crate::provider_args::NativeProviderArg::Codex),
        path: Some(path.to_path_buf()),
        history_source: None,
        history_source_manifest: Vec::new(),
        reset_cursor: false,
        input_format: None,
        all: false,
        resume: false,
        partial: false,
        no_daemon: true,
        format: JsonOutputFormat::Text,
        progress: ProgressArg::None,
    }
}

fn run_options() -> ImportRunOptions {
    ImportRunOptions {
        progress: ProgressArg::None,
        json: false,
        print_human: false,
        allow_empty_sources: true,
        include_history_source_plugins: false,
        operation: "provider-projection-test",
    }
}

fn import_into(data_root: &Path, sessions: &Path) -> anyhow::Result<()> {
    let args = import_args(sessions);
    let mut telemetry = ImportTelemetry::from_args(&args);
    let mut refreshes = ProviderRefreshCollector::default();
    run_import_internal(
        &args,
        data_root.to_path_buf(),
        &mut telemetry,
        &mut refreshes,
        ProviderRefreshTrigger::Import,
        &AppConfig::default(),
        run_options(),
    )
    .map(|_| ())
}

/// Every table the current schema has that a released v0.25 store does not.
///
/// v47 creates these empty, so the first 0.26 import has nothing to resolve
/// against. A fixture that leaves them populated resolves back through rows the
/// setup import just wrote and stops reproducing the defect.
const RELEASED_STORE_ABSENT_TABLES: [&str; 6] = [
    "capture_source_provider_routes",
    "event_aliases",
    "native_path_source_generation_entities",
    "native_path_source_generations",
    "provider_source_locators",
    "session_aliases",
];

fn raw_connection(db_path: &Path) -> Connection {
    let conn = Connection::open(db_path).unwrap();
    // The projection writer fence is a trigger over a Store-registered scalar
    // function; a raw connection has to provide it to rewrite canonical rows.
    conn.create_scalar_function(
        "ctx_projection_writer_authorized_v1",
        0,
        FunctionFlags::SQLITE_UTF8
            | FunctionFlags::SQLITE_DETERMINISTIC
            | FunctionFlags::SQLITE_INNOCUOUS,
        |_| Ok(1_i64),
    )
    .unwrap();
    conn
}

/// Rewrites an imported store into the shape a released ctx 0.25 store has.
///
/// Faithfulness matters more than convenience here. A store generated by this
/// build carries this build's identity state, and an upgrade over it resolves
/// cleanly against rows the setup import just wrote — so a fixture that is only
/// *shaped* like a released store passes an exact-count assertion while the
/// duplication defect is fully present. Two properties make it real: the tables
/// v0.25 never had are empty, and a different release derived *different row
/// identities*, so this build cannot re-derive the ids already there.
/// `superseded_fixture_duplicates_without_the_trigger` is the standing proof
/// that both hold.
fn released_store_shape(db_path: &Path) {
    {
        // v0.25 had no projection journal, so it also had no writer fence.
        let store = Store::open(db_path).unwrap();
        store.disable_projection_journal().unwrap();
    }
    let conn = raw_connection(db_path);
    conn.execute_batch("PRAGMA foreign_keys = OFF").unwrap();
    for table in RELEASED_STORE_ABSENT_TABLES {
        conn.execute_batch(&format!("DELETE FROM {table}")).unwrap();
    }
    conn.execute_batch(
        "DROP TABLE IF EXISTS ctx_provider_projection_generation;
         DELETE FROM sync_cursors;
         UPDATE capture_sources
            SET source_identity = '46b1b4bc-66b2-773d-89ef-30b895fef4a2';
         UPDATE sessions
            SET role_hint = CASE WHEN is_primary = 1 THEN 'primary' ELSE 'subagent' END;",
    )
    .unwrap();
    // A released catalog row carries exactly these six keys — checked against a
    // real v0.25 database. Leaving this build's NativePath change token behind
    // makes the reader treat every source as unchanged, so the upgrade skips the
    // bodies and the fixture stops reproducing event duplication.
    conn.execute_batch(
        "UPDATE catalog_sessions SET metadata_json = (
             SELECT json_group_object(key, value)
             FROM json_each(catalog_sessions.metadata_json)
             WHERE key IN ('catalog_scope', 'cli_version', 'model_provider',
                           'originator', 'source', 'source_kind')
         )
         WHERE metadata_json IS NOT NULL;",
    )
    .unwrap();
    // Re-key to identities this build does not derive. Without this the upgrade
    // matches the ids already present and duplicates nothing.
    conn.execute_batch(
        "UPDATE events SET capture_source_id = 'ffffffff-' || substr(capture_source_id, 10)
             WHERE capture_source_id IS NOT NULL;
         UPDATE sessions SET capture_source_id = 'ffffffff-' || substr(capture_source_id, 10)
             WHERE capture_source_id IS NOT NULL;
         UPDATE runs SET source_id = 'ffffffff-' || substr(source_id, 10)
             WHERE source_id IS NOT NULL;
         UPDATE files_touched SET source_id = 'ffffffff-' || substr(source_id, 10)
             WHERE source_id IS NOT NULL;
         UPDATE capture_sources SET id = 'ffffffff-' || substr(id, 10);
         UPDATE files_touched SET event_id = 'eeeeeeee-' || substr(event_id, 10)
             WHERE event_id IS NOT NULL;
         UPDATE events SET id = 'eeeeeeee-' || substr(id, 10);
         -- The event dedupe key embeds the capture-source id
         -- (`provider-source:<uuid>:<index>:<hash>`); it has to move with the
         -- source, or this build re-derives the key already present and
         -- reconciles instead of duplicating.
         UPDATE events SET dedupe_key = 'provider-source:ffffffff-' || substr(dedupe_key, 26)
             WHERE dedupe_key LIKE 'provider-source:%';
         PRAGMA user_version = 46;",
    )
    .unwrap();
}

/// Marks the store native without changing a row, as if the trigger did not
/// exist. Only used to demonstrate what the trigger prevents.
fn force_native_generation(db_path: &Path) {
    let conn = raw_connection(db_path);
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS ctx_provider_projection_generation (
             singleton INTEGER PRIMARY KEY NOT NULL CHECK (singleton = 1),
             generation INTEGER NOT NULL CHECK (generation IN (0, 1)),
             observed_schema_version INTEGER NOT NULL CHECK (observed_schema_version >= 0)
         );
         INSERT OR REPLACE INTO ctx_provider_projection_generation
             (singleton, generation, observed_schema_version)
         VALUES (1, 1, 47);",
    )
    .unwrap();
}

fn canonical_counts(db_path: &Path) -> BTreeMap<String, i64> {
    let conn = Connection::open(db_path).unwrap();
    [
        "events",
        "sessions",
        "session_edges",
        "runs",
        "capture_sources",
        "files_touched",
        "catalog_sessions",
        "sync_cursors",
        "provider_source_locators",
        "capture_source_provider_routes",
        "event_search",
    ]
    .into_iter()
    .map(|table| {
        let count = conn
            .query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |row| {
                row.get::<_, i64>(0)
            })
            .unwrap();
        (table.to_owned(), count)
    })
    .collect()
}

fn store_identity(db_path: &Path) -> String {
    Connection::open(db_path)
        .unwrap()
        .query_row(
            "SELECT store_identity FROM canonical_semantic_projection_state WHERE singleton = 1",
            [],
            |row| row.get(0),
        )
        .unwrap()
}

/// Files a rebuild must leave untouched, seeded with recognizable bytes.
fn seed_preserved_state(data_root: &Path) -> BTreeMap<PathBuf, Vec<u8>> {
    let mut preserved = BTreeMap::new();
    let entries: Vec<(PathBuf, Vec<u8>)> = vec![
        (
            data_root.join("config.toml"),
            b"[daemon]\nenabled = false\n[analytics]\nenabled = false\n[search]\nsemantic = true\n"
                .to_vec(),
        ),
        (
            data_root.join("device.json"),
            br#"{"device_id":"preserved-device"}"#.to_vec(),
        ),
        (
            data_root.join("install.json"),
            br#"{"schema_version":1,"install_id":"preserved-install"}"#.to_vec(),
        ),
        (
            data_root.join("usage.sqlite"),
            b"preserved-local-usage-database".to_vec(),
        ),
        (
            data_root.join("vectors.sqlite"),
            b"preserved-semantic-vectors".to_vec(),
        ),
        (
            data_root.join("pro").join("bin").join("ctx-pro"),
            b"preserved-pro-helper".to_vec(),
        ),
        (
            data_root.join("objects").join("ab").join("abcd0123456789"),
            b"preserved-content-addressed-object".to_vec(),
        ),
    ];
    for (path, bytes) in entries {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, &bytes).unwrap();
        preserved.insert(path, bytes);
    }
    preserved
}

fn superseded_store(root: &Path) -> (PathBuf, PathBuf) {
    let data_root = root.join("data");
    fs::create_dir_all(&data_root).unwrap();
    let sessions = corpus(root);
    import_into(&data_root, &sessions).unwrap();
    released_store_shape(&database_path(data_root.clone()));
    (data_root, sessions)
}

fn rebuild(data_root: &Path) -> anyhow::Result<RebuildOutcome> {
    // Provider discovery is replaced so the test never reads the developer's
    // own provider history; only the roots the store recorded are replayed.
    sources::with_discovery(Vec::new(), || {
        run_rebuild(
            data_root,
            &AppConfig::default(),
            ProgressArg::None,
            true,
            true,
        )
    })
}

/// Proves the fixture reproduces the defect, so every assertion built on it
/// means something.
///
/// The trigger is disabled here — the store is marked native without changing a
/// row — and the ordinary import path is allowed to run. If this build could
/// re-derive the released identities it would reconcile and this test would
/// fail, and every other test in this file would be passing over a live defect.
/// It duplicates instead: two capture sources where a fresh install has one,
/// and the events of both generations. That is the miniature of 284,923
/// against a fresh install's 142,950.
#[test]
fn superseded_fixture_duplicates_without_the_trigger() {
    let temp = tempdir().unwrap();
    let (data_root, sessions) = superseded_store(temp.path());
    let db_path = database_path(data_root.clone());
    let released = canonical_counts(&db_path);

    let fresh_root = temp.path().join("fresh");
    fs::create_dir_all(&fresh_root).unwrap();
    import_into(&fresh_root, &sessions).unwrap();
    let fresh = canonical_counts(&database_path(fresh_root));

    force_native_generation(&db_path);
    import_into(&data_root, &sessions).expect("the unfenced upgrade import still succeeds");

    let upgraded = canonical_counts(&db_path);
    assert_eq!(
        upgraded["capture_sources"],
        released["capture_sources"] + fresh["capture_sources"],
        "an unfenced upgrade must mint its own capture sources and leave the released \
         ones behind; if it does not, this fixture is not a released store and every \
         assertion built on it is vacuous"
    );
    assert_eq!(
        upgraded["events"],
        released["events"] + fresh["events"],
        "an unfenced upgrade must hold both generations of events"
    );
    assert!(
        upgraded["events"] > fresh["events"],
        "the defect is that the upgraded store exceeds the fresh-install set"
    );
}

#[test]
fn upgraded_store_is_fenced_out_of_provider_imports() {
    let temp = tempdir().unwrap();
    let (data_root, sessions) = superseded_store(temp.path());
    let before = canonical_counts(&database_path(data_root.clone()));

    let error = import_into(&data_root, &sessions).unwrap_err();

    assert!(
        format!("{error}").contains(REBUILD_COMMAND),
        "the refusal must name the command that fixes it: {error}"
    );
    assert_eq!(
        canonical_counts(&database_path(data_root.clone())),
        before,
        "a refused import must not add a single canonical row"
    );
    assert_eq!(observe(&data_root), ProjectionState::RebuildRequired);
    assert_eq!(
        status_json(&data_root)["rebuild_command"],
        json!(REBUILD_COMMAND)
    );
}

#[test]
fn rebuild_reproduces_a_fresh_install_of_the_same_corpus() {
    let temp = tempdir().unwrap();
    let (data_root, sessions) = superseded_store(temp.path());
    let db_path = database_path(data_root.clone());
    let superseded_identity = store_identity(&db_path);

    let fresh_root = temp.path().join("fresh");
    fs::create_dir_all(&fresh_root).unwrap();
    import_into(&fresh_root, &sessions).unwrap();
    let expected = canonical_counts(&database_path(fresh_root));

    let outcome = rebuild(&data_root).unwrap();

    assert!(matches!(outcome, RebuildOutcome::Rebuilt(_)));
    assert_eq!(
        canonical_counts(&db_path),
        expected,
        "an upgraded store must end at the fresh-install result, with no duplicates"
    );
    assert_eq!(observe(&data_root), ProjectionState::Native);
    assert_ne!(
        store_identity(&db_path),
        superseded_identity,
        "the semantic sidecar must see a new Store identity and reconcile"
    );
    let conn = Connection::open(&db_path).unwrap();
    assert_eq!(
        conn.query_row("PRAGMA integrity_check", [], |row| row.get::<_, String>(0))
            .unwrap(),
        "ok"
    );
    assert_eq!(
        conn.prepare("PRAGMA foreign_key_check")
            .unwrap()
            .query_map([], |_| Ok(()))
            .unwrap()
            .count(),
        0
    );
    let (events, distinct) = conn
        .query_row(
            "SELECT COUNT(*), COUNT(DISTINCT id) FROM events",
            [],
            |row| Ok((row.get::<_, i64>(0)?, row.get::<_, i64>(1)?)),
        )
        .unwrap();
    assert_eq!(events, distinct);
    conn.query_row(
        "SELECT COUNT(*) FROM event_search WHERE event_search MATCH 'projection'",
        [],
        |row| row.get::<_, i64>(0),
    )
    .expect("the rebuilt search index must be queryable");
}

#[test]
fn rebuild_keeps_every_local_file_except_the_provider_index() {
    let temp = tempdir().unwrap();
    let (data_root, _) = superseded_store(temp.path());
    let preserved = seed_preserved_state(&data_root);
    let before_index = fs::read(database_path(data_root.clone())).unwrap();

    rebuild(&data_root).unwrap();

    for (path, bytes) in &preserved {
        assert_eq!(
            fs::read(path).ok().as_ref(),
            Some(bytes),
            "{} must survive the rebuild byte for byte",
            path.display()
        );
    }
    assert_ne!(
        fs::read(database_path(data_root.clone())).unwrap(),
        before_index,
        "the provider index itself is the one thing that is replaced"
    );
    assert!(
        !staging_root(&data_root).exists(),
        "the rebuild stage must not survive a successful publication"
    );
    assert!(
        !retired_store_path(&database_path(data_root)).exists(),
        "the superseded generation must not be left behind"
    );
}

#[test]
fn rebuild_is_a_no_op_the_second_time_and_on_a_fresh_install() {
    let temp = tempdir().unwrap();
    let (data_root, _) = superseded_store(temp.path());

    rebuild(&data_root).unwrap();
    let after_first = canonical_counts(&database_path(data_root.clone()));

    let second = rebuild(&data_root).unwrap();

    assert_eq!(second, RebuildOutcome::AlreadyNative);
    assert_eq!(canonical_counts(&database_path(data_root)), after_first);

    let empty = temp.path().join("brand-new");
    fs::create_dir_all(&empty).unwrap();
    let fresh = rebuild(&empty).unwrap();
    assert_eq!(fresh, RebuildOutcome::Uninitialized);
    assert!(!database_path(empty.clone()).exists());
    assert!(!staging_root(&empty).exists());
}

#[test]
fn interrupted_publication_restores_the_original_index_and_a_retry_completes() {
    let temp = tempdir().unwrap();
    let (data_root, _) = superseded_store(temp.path());
    let db_path = database_path(data_root.clone());
    let original = fs::read(&db_path).unwrap();

    // Reproduce process death inside the one-rename window: the index is
    // retired and the replacement is not linked yet.
    let retired = retired_store_path(&db_path);
    fs::rename(&db_path, &retired).unwrap();
    assert!(!db_path.exists());

    rederive::recover_interrupted_publication(&db_path).unwrap();

    assert_eq!(fs::read(&db_path).unwrap(), original);
    assert!(!retired.exists());
    let outcome = rebuild(&data_root).unwrap();
    assert!(matches!(outcome, RebuildOutcome::Rebuilt(_)));
    assert_eq!(observe(&data_root), ProjectionState::Native);
}

#[test]
fn completed_publication_leaves_no_retired_generation_behind() {
    let temp = tempdir().unwrap();
    let (data_root, _) = superseded_store(temp.path());
    let db_path = database_path(data_root);
    let retired = retired_store_path(&db_path);
    fs::write(&retired, b"superseded generation").unwrap();

    rederive::recover_interrupted_publication(&db_path).unwrap();

    assert!(!retired.exists());
    assert!(db_path.exists());
}

#[test]
fn abandoned_rebuild_stage_is_cleared_before_the_next_attempt() {
    let temp = tempdir().unwrap();
    let (data_root, _) = superseded_store(temp.path());
    let staging = staging_root(&data_root);
    fs::create_dir_all(staging.join("objects")).unwrap();
    fs::write(staging.join("work.sqlite"), b"half-written generation").unwrap();
    let original = fs::read(database_path(data_root.clone())).unwrap();

    let outcome = rebuild(&data_root).unwrap();

    assert!(matches!(outcome, RebuildOutcome::Rebuilt(_)));
    assert_ne!(
        fs::read(database_path(data_root.clone())).unwrap(),
        original
    );
    assert!(!staging.exists());
}

#[test]
fn insufficient_disk_refuses_the_rebuild_and_leaves_the_index_installed() {
    let temp = tempdir().unwrap();
    let (data_root, _) = superseded_store(temp.path());
    let db_path = database_path(data_root.clone());
    let before = canonical_counts(&db_path);

    let error = disk::with_available_space(4096, || rebuild(&data_root)).unwrap_err();

    let message = format!("{error}");
    assert!(message.contains("not enough free disk space"), "{message}");
    assert!(message.contains("required"), "{message}");
    assert!(message.contains("available"), "{message}");
    assert_eq!(
        canonical_counts(&db_path),
        before,
        "a refused rebuild must not change a single canonical row"
    );
    assert!(!staging_root(&data_root).exists());
    assert!(!retired_store_path(&db_path).exists());
    assert_eq!(observe(&data_root), ProjectionState::RebuildRequired);

    // With headroom back, the same store rebuilds.
    assert!(matches!(
        rebuild(&data_root).unwrap(),
        RebuildOutcome::Rebuilt(_)
    ));
}

#[test]
fn insufficient_disk_message_names_required_and_available_space() {
    let temp = tempdir().unwrap();
    let db_path = temp.path().join("work.sqlite");
    fs::write(&db_path, vec![0_u8; 4096]).unwrap();
    let headroom = disk::Headroom {
        installed_bytes: 42 * 1024 * 1024 * 1024,
        required_bytes: disk::required_bytes(42 * 1024 * 1024 * 1024),
        available_bytes: 3 * 1024 * 1024 * 1024,
    };

    assert!(!headroom.is_sufficient());
    let message = format!("{}", disk::insufficient_disk_error(&db_path, headroom));
    assert!(message.contains("52.5 GiB"), "{message}");
    assert!(message.contains("3.0 GiB"), "{message}");
    assert!(message.contains("current index is untouched"), "{message}");
    assert_eq!(fs::read(&db_path).unwrap().len(), 4096);
}

#[test]
fn required_headroom_covers_a_second_generation_with_a_floor() {
    // 70 GB of corpus is about 24 GiB of index, and both generations exist at
    // once while the replacement is built.
    let index = 24_u64 * 1024 * 1024 * 1024;
    assert_eq!(disk::required_bytes(index), index / 4 * 5);
    assert_eq!(disk::required_bytes(0), 256 * 1024 * 1024);
    assert!(disk::required_bytes(1024) >= 256 * 1024 * 1024);
}

#[test]
fn recorded_roots_replay_sources_discovery_would_never_find() {
    let temp = tempdir().unwrap();
    let (data_root, sessions) = superseded_store(temp.path());

    let recorded = sources::recorded_roots(&database_path(data_root)).unwrap();

    assert!(
        recorded
            .iter()
            .any(|root| root.provider == CaptureProvider::Codex && root.path == sessions),
        "the store must be able to name the roots it projected: {recorded:?}"
    );
    let replay = sources::replayable_roots(&recorded, &[]);
    assert_eq!(replay.len(), 1);
    assert_eq!(replay[0].path, sessions);

    // A root discovery already covers is not replayed twice.
    let discovered = vec![explicit_path_source(CaptureProvider::Codex, sessions)];
    assert!(sources::replayable_roots(&recorded, &discovered).is_empty());
}
