# Generated by core/apps/web/scripts/generate-playwright-browser-lock.mjs
# Generated at: 2026-05-05T00:00:00.000Z
# Playwright version: 1.57.0

PLAYWRIGHT_BROWSER_RUNTIME_LOCK = {
    "mac15-arm64": {
        "chromium": {
            "directory_name": "chromium-1200",
            "sha256": "01046b12151b2846b6d34ff619336b6338ca254c47aacc903602dd96afc939b3",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-mac-arm64.zip",
        },
        "chromium-headless-shell": {
            "directory_name": "chromium_headless_shell-1200",
            "sha256": "e1620402b69716fa17e38e394c34121ac64c054251803cb13dde58458136e03c",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-headless-shell-mac-arm64.zip",
        },
        "ffmpeg": {
            "directory_name": "ffmpeg-1011",
            "sha256": "7d77eb0d44b59acc4065faa2476c0df1a242cc904c346f820626818c953c5277",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-mac-arm64.zip",
        },
        "firefox": {
            "directory_name": "firefox-1497",
            "sha256": "fed31d85a35d117f28a67416b76e190e41e7e2ada66309266d89b9cb0d6d03ee",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1497/firefox-mac-arm64.zip",
        },
        "webkit": {
            "directory_name": "webkit-2227",
            "sha256": "70a6d62ce9f0280c6a56e0b548e98b4eeebd29be047769a6381c23e568034f44",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2227/webkit-mac-15-arm64.zip",
        },
    },
    "ubuntu24.04-x64": {
        "chromium": {
            "directory_name": "chromium-1200",
            "sha256": "ab56b2a7955c2961f74348e2349f1e907489283da23dba37c730b624e4d670bb",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-linux.zip",
        },
        "chromium-headless-shell": {
            "directory_name": "chromium_headless_shell-1200",
            "sha256": "a9a525cb3832d59a810f78f8ba6c5ed3592a6a488984627f5d827c2a365c8a5a",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-headless-shell-linux.zip",
        },
        "ffmpeg": {
            "directory_name": "ffmpeg-1011",
            "sha256": "ebc74fc5b94830176a3c2914ae96bd8bc7f6a91f4f33890230f84a172ee61ccc",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip",
        },
        "firefox": {
            "directory_name": "firefox-1497",
            "sha256": "168e69855d6e49997823fe765d66f02720f6add035a9d3ac94e51073d391a272",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1497/firefox-ubuntu-24.04.zip",
        },
        "webkit": {
            "directory_name": "webkit-2227",
            "sha256": "e5a1ba6010d3d3b71819b294185131e427f00f48b4ccaa55c640e08d61f6a64f",
            "url": "https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2227/webkit-ubuntu-24.04.zip",
        },
    },
}
