"""Canonical public format and ci/nightly test inventories."""

RUST_FORMAT_TARGETS = [
    "//crates/ctx-cli:analytics_identity_tests",
    "//crates/ctx-cli:analytics_tests",
    "//crates/ctx-cli:analytics_policy_tests",
    "//crates/ctx-cli:auto_upgrade_acceptance_tests",
    "//crates/ctx-cli:cli_public_help_docs_tests",
    "//crates/ctx-cli:cloud_removed_tests",
    "//crates/ctx-cli:custom_root_discovery_tests",
    "//crates/ctx-cli:explicit_path_revision_upgrade_tests",
    "//crates/ctx-cli:history_source_plugins_tests",
    "//crates/ctx-cli:import_change_reporting_tests",
    "//crates/ctx-cli:index_tests",
    "//crates/ctx-cli:integrations_mcp_tests",
    "//crates/ctx-cli:integrations_tests",
    "//crates/ctx-cli:local_usage_tests",
    "//crates/ctx-cli:mcp_attribution_privacy_tests",
    "//crates/ctx-cli:mcp_integration_e2e_tests",
    "//crates/ctx-cli:mcp_local_usage_v2_tests",
    "//crates/ctx-cli:mcp_telemetry_tests",
    "//crates/ctx-cli:mcp_tests",
    "//crates/ctx-cli:native_provider_real_shapes_tests",
    "//crates/ctx-cli:native_provider_rejections_tests",
    "//crates/ctx-cli:native_providers_tests",
    "//crates/ctx-cli:offline_default_tests",
    "//crates/ctx-cli:pro_host_tests",
    "//crates/ctx-cli:pro_lifecycle_tests",
    "//crates/ctx-cli:pro_mcp_tests",
    "//crates/ctx-cli:pro_release_helper_tests",
    "//crates/ctx-cli:pro_test_control_tests",
    "//crates/ctx-cli:pro_test_support_tests",
    "//crates/ctx-cli:raw_output_policy_tests",
    "//crates/ctx-cli:search_refresh_tests",
    "//crates/ctx-cli:search_show_tests",
    "//crates/ctx-cli:setup_sources_import_tests",
    "//crates/ctx-cli:skill_tests",
    "//crates/ctx-cli:slash_command_e2e_tests",
    "//crates/ctx-cli:self_contained_core_content_tests",
    "//crates/ctx-cli:status_store_cutover_tests",
    "//crates/ctx-cli:stats_tests",
    "//crates/ctx-cli:unit_tests",
    "//crates/ctx-cli:upgrade_tests",
    "//crates/ctx-cli:upgrade_analytics_tests",
    "//crates/ctx-history-capture:codex_direct_result_tests",
    "//crates/ctx-history-capture:repository_shell_outcomes_tests",
    "//crates/ctx-history-capture:self_contained_core_final_locator_removal_tests",
    "//crates/ctx-history-capture:unit_tests",
    "//crates/ctx-history-core:unit_tests",
    "//crates/ctx-history-index:mcp_attribution_search_tests",
    "//crates/ctx-history-index:source_backed_recovery_tests",
    "//crates/ctx-history-index:unit_tests",
    "//crates/ctx-history-refresh:unit_tests",
    "//crates/ctx-pro-host-protocol:generate_protocol_inventory",
    "//crates/ctx-pro-host-protocol:unit_tests",
    "//crates/ctx-protocol:unit_tests",
    "//crates/ctx-sdk:unit_tests",
]

# Provider correctness is ordinary executable CI, not a second evidence system.
#
# The focused capture target fail-closes on an exact reviewed inventory of
# active-writer seams across JSONL, SQLite-WAL, document/tree, and event-file
# families. The CLI targets prove real-shape admission/rejection, discovery,
# refresh, and user-facing self-contained Core behavior.
_CI_PROVIDER_TESTS = [
    "//crates/ctx-cli:mcp_attribution_privacy_tests",
    "//crates/ctx-cli:native_provider_real_shapes_tests",
    "//crates/ctx-cli:native_provider_rejections_tests",
    "//crates/ctx-cli:native_providers_tests",
    "//crates/ctx-cli:search_refresh_tests",
    "//crates/ctx-cli:setup_sources_import_tests",
    "//crates/ctx-cli:self_contained_core_content_tests",
    "//crates/ctx-history-capture:active_source_family_contract_tests",
    "//crates/ctx-history-capture:mcp_attribution_conformance_runner_tests",
    "//crates/ctx-history-capture:mcp_attribution_conformance_tests",
    "//crates/ctx-history-capture:self_contained_core_final_locator_removal_tests",
    "//crates/ctx-history-capture:unit_tests",
    "//crates/ctx-history-index:mcp_attribution_search_tests",
]

_CI_RUST_TESTS = [
    ":native_ctx_binary_smoke",
    "//crates/ctx-cli:analytics_identity_tests",
    "//crates/ctx-cli:analytics_tests",
    "//crates/ctx-cli:analytics_policy_tests",
    "//crates/ctx-cli:cli_public_help_docs_tests",
    "//crates/ctx-cli:cloud_removed_tests",
    "//crates/ctx-cli:custom_root_discovery_tests",
    "//crates/ctx-cli:explicit_path_revision_upgrade_tests",
    "//crates/ctx-cli:history_source_plugins_tests",
    "//crates/ctx-cli:import_change_reporting_tests",
    "//crates/ctx-cli:index_tests",
    "//crates/ctx-cli:integrations_mcp_tests",
    "//crates/ctx-cli:integrations_tests",
    "//crates/ctx-cli:local_usage_tests",
    "//crates/ctx-cli:mcp_integration_e2e_tests",
    "//crates/ctx-cli:mcp_local_usage_v2_tests",
    "//crates/ctx-cli:mcp_telemetry_tests",
    "//crates/ctx-cli:mcp_tests",
    "//crates/ctx-cli:offline_default_tests",
    "//crates/ctx-cli:pro_host_tests",
    "//crates/ctx-cli:pro_lifecycle_tests",
    "//crates/ctx-cli:pro_mcp_tests",
    "//crates/ctx-cli:pro_release_helper_tests",
    "//crates/ctx-cli:pro_test_control_tests",
    "//crates/ctx-cli:pro_test_support_tests",
    "//crates/ctx-cli:raw_output_policy_tests",
    "//crates/ctx-cli:search_show_tests",
    "//crates/ctx-cli:skill_tests",
    "//crates/ctx-cli:slash_command_e2e_tests",
    "//crates/ctx-cli:status_store_cutover_tests",
    "//crates/ctx-cli:stats_tests",
    "//crates/ctx-cli:unit_tests",
    "//crates/ctx-cli:upgrade_tests",
    "//crates/ctx-cli:upgrade_analytics_tests",
    "//crates/ctx-history-capture:codex_direct_result_tests",
    "//crates/ctx-history-capture:repository_shell_outcomes_tests",
    "//crates/ctx-history-core:unit_tests",
    "//crates/ctx-history-index:migration_fault_tests",
    "//crates/ctx-history-index:source_backed_recovery_tests",
    "//crates/ctx-history-index:unit_tests",
    "//crates/ctx-history-refresh:unit_tests",
    "//crates/ctx-pro-host-protocol:conformance_tests",
    "//crates/ctx-pro-host-protocol:unit_tests",
    "//crates/ctx-protocol:unit_tests",
    "//crates/ctx-sdk:unit_tests",
]

# Merge validation owns every deterministic format, policy, SDK, unit,
# contract, and bounded integration check. Keep these as direct targets so CI
# has one aggregate graph instead of routing through overlapping aliases.
CI_TESTS = [
    ":bazel_affected_mutation_tests",
    ":bazel_affected_script_tests",
    ":bazel_wrapper_tests",
    ":buildkite_pipeline_check",
    ":cargo_diagnostic_tests",
    ":check_force_rerun_tests",
    ":cli_build_cfg_parity_check",
    ":cli_ux_capture_cleanup_tests",
    ":cli_ux_observer_tests",
    ":dependency_advisory_gate_tests",
    ":detached_debug_symbols_tests",
    ":docs_check",
    ":freebsd_ort_exit_contract",
    ":freebsd_ort_exit_contract_mutation_tests",
    ":installer_path_smoke",
    ":linux_bazel_controller_receipt_tests",
    ":linux_bazel_release_publication_tests",
    ":linux_release_construction_tests",
    ":loc_check",
    ":macos_release_signing_tests",
    ":native_bazel_packaging_contract_tests",
    ":native_candidate_smoke_tests",
    ":onnxruntime_sidecar_tools_tests",
    ":package_audit_fast",
    ":package_audit_release",
    ":public_cli_artifact_cleanup_tests",
    ":public_cli_bazel_build_info_tests",
    ":public_cli_bazel_release_contract",
    ":public_cli_release_targets_tests",
    ":public_control_surface_check",
    ":release_binary_compat_tests",
    ":release_binary_string_audit_tests",
    ":release_sbom_tests",
    ":release_source_surface_audit_tests",
    ":release_target_matrix_check",
    ":release_target_matrix_tests",
    ":rust_target_inventory_check",
    ":rust_toolchain_pin_check",
    ":rust_toolchain_pin_mutation_tests",
    ":rustfmt_check",
    ":sdk_contract_checks",
    ":sdk_no_publish_policy_tests",
    ":sdk_package_dry_run",
    ":source_diff_check",
    ":stage_github_release_assets_tests",
    ":stage_semantic_release_handoff_tests",
    ":test_tier_inventory_check",
    "//crates/ctx-cli:daemon_config_reload_tests",
    "//crates/ctx-cli:search_source_identity_filters_tests",
    "//crates/ctx-pro-host-protocol:protocol_inventory_regeneration_test",
    "//sdks/go:go_sdk_tests",
    "//sdks/go/examples/dogfood:dogfood_tests",
    "//tools/bazel:release_route_analysis_tests",
    "//tools/bazel:test_tier_inventory_tests",
] + _CI_RUST_TESTS + _CI_PROVIDER_TESTS

# Nightly adds performance sanity plus the intentionally serialized upgrade,
# daemon, and injected process/filesystem fault qualification that should not
# run on every merge.
NIGHTLY_TESTS = [
    ":performance_sanity_tests",
    "//crates/ctx-cli:auto_upgrade_acceptance_tests",
    "//crates/ctx-cli:persistent_daemon_lifecycle_tests",
    "//crates/ctx-history-index:migration_disk_qualification_tests",
    "//scripts/source-backed-recovery:fault_qualification",
]
