"""Canonical public format and ci/nightly test inventories."""

RUST_FORMAT_TARGETS = [
    "//crates/ctx-cli:analytics_identity_tests",
    "//crates/ctx-cli:analytics_tests",
    "//crates/ctx-cli:analytics_policy_tests",
    "//crates/ctx-cli:auto_upgrade_acceptance_tests",
    "//crates/ctx-cli:cli_public_help_docs_tests",
    "//crates/ctx-cli:cloud_removed_tests",
    "//crates/ctx-cli:custom_root_discovery_tests",
    "//crates/ctx-cli:explicit_path_revision_upgrade_tests",
    "//crates/ctx-cli:history_source_plugins_tests",
    "//crates/ctx-cli:import_change_reporting_tests",
    "//crates/ctx-cli:index_tests",
    "//crates/ctx-cli:integrations_mcp_tests",
    "//crates/ctx-cli:integrations_tests",
    "//crates/ctx-cli:local_usage_tests",
    "//crates/ctx-cli:mcp_integration_e2e_tests",
    "//crates/ctx-cli:mcp_local_usage_v2_tests",
    "//crates/ctx-cli:mcp_telemetry_tests",
    "//crates/ctx-cli:mcp_tests",
    "//crates/ctx-cli:native_provider_real_shapes_tests",
    "//crates/ctx-cli:native_provider_rejections_tests",
    "//crates/ctx-cli:native_providers_tests",
    "//crates/ctx-cli:offline_default_tests",
    "//crates/ctx-cli:pro_host_tests",
    "//crates/ctx-cli:pro_lifecycle_tests",
    "//crates/ctx-cli:pro_mcp_tests",
    "//crates/ctx-cli:pro_release_helper_tests",
    "//crates/ctx-cli:pro_test_support_tests",
    "//crates/ctx-cli:search_refresh_tests",
    "//crates/ctx-cli:search_show_locate_sql_tests",
    "//crates/ctx-cli:setup_sources_import_tests",
    "//crates/ctx-cli:skill_tests",
    "//crates/ctx-cli:slash_command_e2e_tests",
    "//crates/ctx-cli:source_backed_content_tests",
    "//crates/ctx-cli:status_store_cutover_tests",
    "//crates/ctx-cli:stats_tests",
    "//crates/ctx-cli:unit_tests",
    "//crates/ctx-cli:upgrade_tests",
    "//crates/ctx-cli:upgrade_analytics_tests",
    "//crates/ctx-history-capture:complete_content_sqlite_tests",
    "//crates/ctx-history-capture:unit_tests",
    "//crates/ctx-history-core:unit_tests",
    "//crates/ctx-history-index:source_backed_recovery_tests",
    "//crates/ctx-history-index:unit_tests",
    "//crates/ctx-history-relational:unit_tests",
    "//crates/ctx-pro-host-protocol:generate_protocol_inventory",
    "//crates/ctx-pro-host-protocol:unit_tests",
    "//crates/ctx-protocol:unit_tests",
    "//crates/ctx-sdk:unit_tests",
]

_CI_PROVIDER_TESTS = [
    "//crates/ctx-cli:native_provider_real_shapes_tests",
    "//crates/ctx-cli:native_provider_rejections_tests",
    "//crates/ctx-cli:native_providers_tests",
    "//crates/ctx-cli:search_refresh_tests",
    "//crates/ctx-cli:setup_sources_import_tests",
    "//crates/ctx-cli:source_backed_content_tests",
    "//crates/ctx-history-capture:complete_content_tests",
]

_CI_RUST_TESTS = [
    ":native_ctx_binary_smoke",
    "//crates/ctx-cli:analytics_identity_tests",
    "//crates/ctx-cli:analytics_tests",
    "//crates/ctx-cli:analytics_policy_tests",
    "//crates/ctx-cli:cli_public_help_docs_tests",
    "//crates/ctx-cli:cloud_removed_tests",
    "//crates/ctx-cli:custom_root_discovery_tests",
    "//crates/ctx-cli:explicit_path_revision_upgrade_tests",
    "//crates/ctx-cli:history_source_plugins_tests",
    "//crates/ctx-cli:import_change_reporting_tests",
    "//crates/ctx-cli:index_tests",
    "//crates/ctx-cli:integrations_mcp_tests",
    "//crates/ctx-cli:integrations_tests",
    "//crates/ctx-cli:local_usage_tests",
    "//crates/ctx-cli:mcp_integration_e2e_tests",
    "//crates/ctx-cli:mcp_local_usage_v2_tests",
    "//crates/ctx-cli:mcp_telemetry_tests",
    "//crates/ctx-cli:mcp_tests",
    "//crates/ctx-cli:offline_default_tests",
    "//crates/ctx-cli:pro_host_tests",
    "//crates/ctx-cli:pro_lifecycle_tests",
    "//crates/ctx-cli:pro_mcp_tests",
    "//crates/ctx-cli:pro_release_helper_tests",
    "//crates/ctx-cli:pro_test_support_tests",
    "//crates/ctx-cli:search_show_locate_sql_tests",
    "//crates/ctx-cli:skill_tests",
    "//crates/ctx-cli:slash_command_e2e_tests",
    "//crates/ctx-cli:status_store_cutover_tests",
    "//crates/ctx-cli:stats_tests",
    "//crates/ctx-cli:unit_tests",
    "//crates/ctx-cli:upgrade_tests",
    "//crates/ctx-cli:upgrade_analytics_tests",
    "//crates/ctx-history-core:unit_tests",
    "//crates/ctx-history-index:source_backed_recovery_tests",
    "//crates/ctx-history-index:unit_tests",
    "//crates/ctx-history-relational:unit_tests",
    "//crates/ctx-pro-host-protocol:conformance_tests",
    "//crates/ctx-pro-host-protocol:unit_tests",
    "//crates/ctx-protocol:unit_tests",
    "//crates/ctx-sdk:unit_tests",
]

# Merge validation owns every deterministic format, policy, SDK, unit,
# contract, and bounded integration check. Keep these as direct targets so CI
# has one aggregate graph instead of routing through overlapping aliases.
CI_TESTS = [
    ":bazel_affected_mutation_tests",
    ":bazel_affected_script_tests",
    ":bazel_wrapper_tests",
    ":buildkite_pipeline_check",
    ":cargo_diagnostic_tests",
    ":check_force_rerun_tests",
    ":cli_build_cfg_parity_check",
    ":dependency_advisory_gate_tests",
    ":docs_check",
    ":freebsd_ort_exit_contract",
    ":freebsd_ort_exit_contract_mutation_tests",
    ":installer_path_smoke",
    ":linux_release_construction_tests",
    ":loc_check",
    ":macos_release_signing_tests",
    ":native_bazel_packaging_contract_tests",
    ":native_candidate_smoke_tests",
    ":package_audit_fast",
    ":package_audit_release",
    ":public_cli_artifact_cleanup_tests",
    ":public_cli_bazel_build_info_tests",
    ":public_cli_bazel_release_contract",
    ":public_cli_release_targets_tests",
    ":public_control_surface_check",
    ":release_binary_compat_tests",
    ":release_binary_string_audit_tests",
    ":release_sbom_tests",
    ":release_source_surface_audit_tests",
    ":release_target_matrix_check",
    ":release_target_matrix_tests",
    ":rust_target_inventory_check",
    ":rust_toolchain_pin_check",
    ":rust_toolchain_pin_mutation_tests",
    ":rustfmt_check",
    ":sdk_contract_checks",
    ":sdk_package_dry_run",
    ":source_diff_check",
    ":stage_github_release_assets_tests",
    "//crates/ctx-cli:daemon_config_reload_tests",
    "//crates/ctx-cli:search_source_identity_filters_tests",
    "//sdks/go:go_sdk_tests",
    "//sdks/go/examples/dogfood:dogfood_tests",
    "//tools/bazel:release_route_analysis_tests",
] + _CI_RUST_TESTS + _CI_PROVIDER_TESTS

# Nightly adds performance sanity plus the intentionally serialized upgrade,
# daemon, and injected process/filesystem fault qualification that should not
# run on every merge.
NIGHTLY_TESTS = [
    ":performance_sanity_tests",
    "//crates/ctx-cli:auto_upgrade_acceptance_tests",
    "//crates/ctx-cli:persistent_daemon_lifecycle_tests",
    "//crates/ctx-cli:pro_qualification_tests",
    "//scripts/source-backed-recovery:fault_qualification",
]
