export {
  initAnalytics,
  setAnalyticsEnabled,
  captureAnalyticsEvent,
  captureProductEvent,
  captureIncidentEvent,
} from "./client";

export { getFeatureGate, useFeatureGate } from "./featureGates";

export {
  trackAppOpened,
  trackWorkspaceCreated,
  trackWorkspaceCreateSubmitted,
  trackWorkspaceCreateSucceeded,
  trackWorkspaceCreateFailed,
  trackWorkspaceLaunchCompleted,
  trackWorkspaceOpened,
  trackWorkspaceRouteOpenedFromPending,
  trackWizardStarted,
  trackWizardStepViewed,
  trackWizardStepCompleted,
  trackWizardCompleted,
  trackWizardAbandoned,
  trackSessionCreated,
  trackTaskCreated,
  trackProviderSelected,
  trackProviderInstallStarted,
  trackProviderInstallCompleted,
  trackProviderInstallFailed,
  trackProviderAuthStarted,
  trackProviderAuthCompleted,
  trackProviderAuthFailed,
  trackFirstTurnSubmitted,
  trackUserMessageSent,
  trackTurnStarted,
  trackTurnCompleted,
  trackFirstTurnCompleted,
  trackProviderRunCompleted,
  normalizeProviderInstallFailureKind,
  normalizeProviderAuthFailureKind,
  normalizeTurnFailureKind,
  trackFeatureUsed,
  trackWorkbenchPanelToggled,
  trackPlanViewed,
  trackSubscribeCtaClicked,
  trackCheckoutStarted,
  trackEntitlementActivated,
  trackFeatureGateEvaluated,
  trackExperimentExposure,
  trackRuntimeErrorObserved,
  trackSessionLoadFatalObserved,
  trackApiErrorObserved,
  trackDesktopWebviewRecoveryObserved,
  trackForegroundFreshnessSlaMissed,
  trackForegroundBacklogObserved,
  trackForegroundGapRecoveryObserved,
  trackRendererBacklogSample,
  trackRendererBacklogSpike,
  trackFreshnessRecovered,
  trackWorkerPatchFlush,
  trackWorkerPatchApply,
  trackUnknownEventBurst,
  trackSessionEventVolumeBurst,
  trackRendererHeartbeatMissed,
} from "./activity";

export type {
  ProviderAuthFailureKind,
  ProviderAuthMethod,
  ProviderInstallFailureKind,
  ProviderSetupSource,
  TurnFailureKind,
} from "./activity";

export { sanitizeAnalyticsProperties } from "./schema";

export {
  normalizeDownloadAttributionId,
  createDownloadAttributionId,
  appendDownloadAttributionIdToUrl,
  setPendingDownloadAttributionId,
  getPendingDownloadAttributionId,
  clearPendingDownloadAttributionId,
  consumePendingDownloadAttributionId,
} from "./downloadAttribution";
