import type { CSSProperties } from "react";
import {
  SESSION_THREAD_GEOMETRY_REVISION,
  SESSION_THREAD_GEOMETRY_SPEC,
  type SessionThreadGeometrySpec,
  resolveSessionThreadAskUserShellHeightPx,
  resolveSessionThreadContentMaxWidthPx,
  resolveSessionThreadMarkdownBlockquoteInsetPx,
  resolveSessionThreadMarkdownInlineCodeEdgeBlockPx,
  resolveSessionThreadMarkdownInlineCodeEdgeInlinePx,
  resolveSessionThreadMarkdownInlineCodeFragmentChromeHeightPx,
  resolveSessionThreadMarkdownInlineCodeFragmentChromeWidthPx,
  resolveSessionThreadThoughtHorizontalChromePx,
  resolveSessionThreadThoughtVerticalChromePx,
  resolveSessionThreadToolSummaryRowHeightPx,
  resolveSessionThreadToolThoughtBodyChromeHeightPx,
  resolveSessionThreadToolThoughtBodyChromeWidthPx,
  resolveSessionThreadToolThoughtTitleHeightPx,
} from "./sessionThreadGeometrySpec";

export type SessionThreadGeometryViews = ReturnType<typeof buildSessionThreadGeometryViews>;

export function buildSessionThreadGeometryViews(
  spec: SessionThreadGeometrySpec = SESSION_THREAD_GEOMETRY_SPEC,
) {
  const geometryRevision = SESSION_THREAD_GEOMETRY_REVISION;
  const contentMaxWidthPx = resolveSessionThreadContentMaxWidthPx(spec);
  const inlineCodeEdgeBlockPx = resolveSessionThreadMarkdownInlineCodeEdgeBlockPx(spec);
  const inlineCodeEdgeInlinePx = resolveSessionThreadMarkdownInlineCodeEdgeInlinePx(spec);
  const inlineCodeFragmentChromeHeightPx =
    resolveSessionThreadMarkdownInlineCodeFragmentChromeHeightPx(spec);
  const inlineCodeFragmentChromeWidthPx =
    resolveSessionThreadMarkdownInlineCodeFragmentChromeWidthPx(spec);
  const markdownBlockquoteInsetPx = resolveSessionThreadMarkdownBlockquoteInsetPx(spec);
  const askUserShellHeightPx = resolveSessionThreadAskUserShellHeightPx(spec);
  const thoughtHorizontalChromePx = resolveSessionThreadThoughtHorizontalChromePx(spec);
  const thoughtVerticalChromePx = resolveSessionThreadThoughtVerticalChromePx(spec);
  const toolSummaryRowHeightPx = resolveSessionThreadToolSummaryRowHeightPx(spec);
  const toolThoughtTitleHeightPx = resolveSessionThreadToolThoughtTitleHeightPx(spec);
  const toolThoughtBodyChromeWidthPx = resolveSessionThreadToolThoughtBodyChromeWidthPx(spec);
  const toolThoughtBodyChromeHeightPx = resolveSessionThreadToolThoughtBodyChromeHeightPx(spec);

  const measurementContract = {
    geometryRevision,
    typography: {
      bodyFontFamily: spec.markdown.typography.bodyFontFamily,
      bodyFontSizePx: spec.markdown.typography.bodyFontSizePx,
      bodyLineHeightPx: spec.markdown.typography.bodyLineHeightPx,
      headingFontSizePxByDepth: spec.markdown.typography.headingFontSizePxByDepth,
      inlineCodeFontFamily: spec.markdown.typography.inlineCodeFontFamily,
      inlineCodeFontSizePx: spec.markdown.typography.inlineCodeFontSizePx,
      codeBlockFontSizePx: spec.markdown.typography.codeBlockFontSizePx,
      codeBlockLineHeightPx: spec.markdown.typography.codeBlockLineHeightPx,
      headingLineHeightPxByDepth: spec.markdown.typography.headingLineHeightPxByDepth,
      fontWeight: spec.markdown.typography.fontWeight,
    },
    inlineCode: {
      paddingBlockPx: spec.markdown.inlineCode.paddingBlockPx,
      paddingInlinePx: spec.markdown.inlineCode.paddingInlinePx,
      borderWidthPx: spec.markdown.inlineCode.borderWidthPx,
      borderRadiusPx: spec.markdown.inlineCode.borderRadiusPx,
      edgeBlockPx: inlineCodeEdgeBlockPx,
      edgeInlinePx: inlineCodeEdgeInlinePx,
      fragmentChromeHeightPx: inlineCodeFragmentChromeHeightPx,
      fragmentChromeWidthPx: inlineCodeFragmentChromeWidthPx,
    },
    blockSpacing: {
      blockMarginBottomPx: spec.markdown.blockSpacing.blockMarginBottomPx,
      headingMarginTopPx: spec.markdown.blockSpacing.headingMarginTopPx,
      headingMarginBottomPx: spec.markdown.blockSpacing.headingMarginBottomPx,
      entryGapPxByContext: spec.markdown.blockSpacing.entryGapPxByContext,
      exitGapPxByContext: spec.markdown.blockSpacing.exitGapPxByContext,
    },
    list: {
      indentPx: spec.markdown.list.indentPx,
      gapPx: spec.markdown.list.gapPx,
      markerMinWidthPx: spec.markdown.list.markerMinWidthPx,
      markerGapPx: spec.markdown.list.markerGapPx,
      markerAdvancePx: spec.markdown.list.markerAdvancePx,
      checkboxGutterPx: spec.markdown.list.checkboxGutterPx,
    },
    blockquote: {
      borderWidthPx: spec.markdown.blockquote.borderWidthPx,
      paddingInlineStartPx: spec.markdown.blockquote.paddingInlineStartPx,
      insetPx: markdownBlockquoteInsetPx,
    },
    codeBlock: {
      borderWidthPx: spec.markdown.codeBlock.borderWidthPx,
      paddingTopPx: spec.markdown.codeBlock.paddingTopPx,
      paddingBottomPx: spec.markdown.codeBlock.paddingBottomPx,
    },
    image: {
      widthPx: spec.markdown.image.widthPx,
      heightPx: spec.markdown.image.heightPx,
    },
    table: {
      borderWidthPx: spec.markdown.table.borderWidthPx,
      cellPaddingBlockPx: spec.markdown.table.cellPaddingBlockPx,
      cellPaddingInlinePx: spec.markdown.table.cellPaddingInlinePx,
    },
  } as const;

  const rowMeasurementContract = {
    geometryRevision,
    viewport: {
      rowMaxWidthPx: spec.viewport.rowMaxWidthPx,
      contentMaxWidthPx,
      horizontalInsetPx: spec.viewport.horizontalInsetPx,
      indentLeftPx: spec.viewport.indentLeftPx,
    },
    assistant: {
      entryPaddingInlinePx: spec.rows.assistant.entryPaddingInlinePx,
      verticalPaddingPx: spec.rows.assistant.verticalPaddingPx,
    },
    message: {
      rowPaddingBlockPx: spec.rows.message.rowPaddingBlockPx,
      bubblePaddingBlockPx: spec.rows.message.bubblePaddingBlockPx,
      bubblePaddingInlinePx: spec.rows.message.bubblePaddingInlinePx,
      bubbleBorderWidthPx: spec.rows.message.bubbleBorderWidthPx,
      maxWidthRatio: spec.rows.message.maxWidthRatio,
      roleFontSizePx: spec.rows.message.roleFontSizePx,
      roleLineHeightPx: spec.rows.message.roleLineHeightPx,
      toggleMarginTopPx: spec.rows.message.toggleMarginTopPx,
      toggleFontSizePx: spec.rows.message.toggleFontSizePx,
      toggleLineHeightPx: spec.rows.message.toggleLineHeightPx,
      attachments: {
        widthPx: spec.rows.message.attachments.widthPx,
        heightPx: spec.rows.message.attachments.heightPx,
        gapPx: spec.rows.message.attachments.gapPx,
        marginTopPx: spec.rows.message.attachments.marginTopPx,
      },
    },
    turnHeader: {
      bubblePaddingBlockPx: spec.rows.turnHeader.bubblePaddingBlockPx,
      bubblePaddingInlinePx: spec.rows.turnHeader.bubblePaddingInlinePx,
      bubbleBorderWidthPx: spec.rows.turnHeader.bubbleBorderWidthPx,
      collapsedMaxHeightPx: spec.rows.turnHeader.collapsedMaxHeightPx,
      copyGutterPx: spec.rows.turnHeader.copyGutterPx,
      outerVerticalPx: spec.rows.turnHeader.outerVerticalPx,
      attachments: {
        sizePx: spec.rows.turnHeader.attachments.sizePx,
        gapPx: spec.rows.turnHeader.attachments.gapPx,
        marginTopPx: spec.rows.turnHeader.attachments.marginTopPx,
      },
    },
    askUser: {
      marginVerticalPx: spec.rows.askUser.marginVerticalPx,
      cardMinWidthPx: spec.rows.askUser.cardMinWidthPx,
      cardMaxWidthPx: spec.rows.askUser.cardMaxWidthPx,
      cardPaddingPx: spec.rows.askUser.cardPaddingPx,
      cardGapPx: spec.rows.askUser.cardGapPx,
      tabsHeightPx: spec.rows.askUser.tabsHeightPx,
      panelHeightPx: spec.rows.askUser.panelHeightPx,
      statusHeightPx: spec.rows.askUser.statusHeightPx,
      actionsHeightPx: spec.rows.askUser.actionsHeightPx,
      hintHeightPx: spec.rows.askUser.hintHeightPx,
      shellHeightPx: askUserShellHeightPx,
      outerHeightPx: spec.rows.askUser.marginVerticalPx + askUserShellHeightPx,
    },
    thought: {
      paddingInlinePx: spec.rows.thought.paddingInlinePx,
      paddingBlockPx: spec.rows.thought.paddingBlockPx,
      horizontalChromePx: thoughtHorizontalChromePx,
      verticalChromePx: thoughtVerticalChromePx,
      typography: spec.rows.thought.typography,
    },
    tools: {
      itemGapPx: spec.rows.tools.itemGapPx,
      groupGapPx: spec.rows.tools.groupGapPx,
      summary: {
        rowHeightPx: toolSummaryRowHeightPx,
        paddingInlinePx: spec.rows.tools.summary.paddingInlinePx,
        paddingBlockPx: spec.rows.tools.summary.paddingBlockPx,
        separatorPaddingInlinePx: spec.rows.tools.summary.separatorPaddingInlinePx,
        statusDotPaddingInlinePx: spec.rows.tools.summary.statusDotPaddingInlinePx,
        typography: spec.rows.tools.summary.typography,
      },
      loading: {
        typography: spec.rows.tools.loading.typography,
      },
      thoughtTitle: {
        heightPx: toolThoughtTitleHeightPx,
        marginBottomPx: spec.rows.tools.thoughtTitle.marginBottomPx,
        typography: spec.rows.tools.thoughtTitle.typography,
      },
      thoughtBody: {
        paddingPx: spec.rows.tools.thoughtBody.paddingPx,
        borderWidthPx: spec.rows.tools.thoughtBody.borderWidthPx,
        chromeWidthPx: toolThoughtBodyChromeWidthPx,
        chromeHeightPx: toolThoughtBodyChromeHeightPx,
        typography: spec.rows.tools.thoughtBody.typography,
      },
    },
    fixed: {
      spacerHeightPx: spec.rows.fixed.spacerHeightPx,
      turnStatusHeightPx: spec.rows.fixed.turnStatusHeightPx,
    },
  } as const;

  const layout = {
    rowMaxWidthPx: spec.viewport.rowMaxWidthPx,
    horizontalInsetPx: spec.viewport.horizontalInsetPx,
    indentLeftPx: spec.viewport.indentLeftPx,
    contentMaxWidthPx,
    markdownBodyFontSizePx: spec.markdown.typography.bodyFontSizePx,
    markdownBodyLineHeightPx: spec.markdown.typography.bodyLineHeightPx,
    markdownBodyFontFamily: spec.markdown.typography.bodyFontFamily,
    markdownHeadingFontSizePxByDepth: spec.markdown.typography.headingFontSizePxByDepth,
    markdownHeadingLineHeightPxByDepth: spec.markdown.typography.headingLineHeightPxByDepth,
    markdownFontWeight: spec.markdown.typography.fontWeight,
    markdownBlockMarginBottomPx: spec.markdown.blockSpacing.blockMarginBottomPx,
    markdownHeadingMarginTopPx: spec.markdown.blockSpacing.headingMarginTopPx,
    markdownHeadingMarginBottomPx: spec.markdown.blockSpacing.headingMarginBottomPx,
    markdownListIndentPx: spec.markdown.list.indentPx,
    markdownListGapPx: spec.markdown.list.gapPx,
    markdownListMarkerMinWidthPx: spec.markdown.list.markerMinWidthPx,
    markdownListMarkerGapPx: spec.markdown.list.markerGapPx,
    markdownListMarkerAdvancePx: spec.markdown.list.markerAdvancePx,
    markdownInlineCodePaddingBlockPx: spec.markdown.inlineCode.paddingBlockPx,
    markdownInlineCodePaddingInlinePx: spec.markdown.inlineCode.paddingInlinePx,
    markdownInlineCodeBorderWidthPx: spec.markdown.inlineCode.borderWidthPx,
    markdownInlineCodeBorderRadiusPx: spec.markdown.inlineCode.borderRadiusPx,
    markdownInlineCodeFontSizePx: spec.markdown.typography.inlineCodeFontSizePx,
    markdownInlineCodeFontFamily: spec.markdown.typography.inlineCodeFontFamily,
    markdownInlineCodeEdgeBlockPx: inlineCodeEdgeBlockPx,
    markdownInlineCodeEdgePx: inlineCodeEdgeInlinePx,
    markdownInlineCodeFragmentChromeHeightPx: inlineCodeFragmentChromeHeightPx,
    markdownInlineCodeFragmentChromeWidthPx: inlineCodeFragmentChromeWidthPx,
    markdownCodeBlockFontSizePx: spec.markdown.typography.codeBlockFontSizePx,
    markdownCodeBlockLineHeightPx: spec.markdown.typography.codeBlockLineHeightPx,
    markdownBlockquoteBorderWidthPx: spec.markdown.blockquote.borderWidthPx,
    markdownBlockquotePaddingInlineStartPx: spec.markdown.blockquote.paddingInlineStartPx,
    markdownBlockquoteInsetPx,
    markdownImageWidthPx: spec.markdown.image.widthPx,
    markdownImageHeightPx: spec.markdown.image.heightPx,
    markdownCodeBlockBorderWidthPx: spec.markdown.codeBlock.borderWidthPx,
    markdownCodeBlockPaddingTopPx: spec.markdown.codeBlock.paddingTopPx,
    markdownCodeBlockPaddingBottomPx: spec.markdown.codeBlock.paddingBottomPx,
    markdownTableBorderWidthPx: spec.markdown.table.borderWidthPx,
    markdownTableCellPaddingBlockPx: spec.markdown.table.cellPaddingBlockPx,
    markdownTableCellPaddingInlinePx: spec.markdown.table.cellPaddingInlinePx,
    messageRowPaddingBlockPx: spec.rows.message.rowPaddingBlockPx,
    messageBubblePaddingBlockPx: spec.rows.message.bubblePaddingBlockPx,
    messageBubblePaddingInlinePx: spec.rows.message.bubblePaddingInlinePx,
    messageBubbleBorderWidthPx: spec.rows.message.bubbleBorderWidthPx,
    messageMaxWidthRatio: spec.rows.message.maxWidthRatio,
    messageRoleFontSizePx: spec.rows.message.roleFontSizePx,
    messageRoleLineHeightPx: spec.rows.message.roleLineHeightPx,
    messageToggleMarginTopPx: spec.rows.message.toggleMarginTopPx,
    messageToggleFontSizePx: spec.rows.message.toggleFontSizePx,
    messageToggleLineHeightPx: spec.rows.message.toggleLineHeightPx,
    messageAttachmentWidthPx: spec.rows.message.attachments.widthPx,
    messageAttachmentHeightPx: spec.rows.message.attachments.heightPx,
    messageAttachmentGapPx: spec.rows.message.attachments.gapPx,
    messageAttachmentMarginTopPx: spec.rows.message.attachments.marginTopPx,
    assistantEntryPaddingInlinePx: spec.rows.assistant.entryPaddingInlinePx,
    turnHeaderBubblePaddingBlockPx: spec.rows.turnHeader.bubblePaddingBlockPx,
    turnHeaderBubblePaddingInlinePx: spec.rows.turnHeader.bubblePaddingInlinePx,
    turnHeaderBubbleBorderWidthPx: spec.rows.turnHeader.bubbleBorderWidthPx,
    turnHeaderCopyGutterPx: spec.rows.turnHeader.copyGutterPx,
    turnHeaderCollapsedMaxHeightPx: spec.rows.turnHeader.collapsedMaxHeightPx,
    askUserMarginVerticalPx: spec.rows.askUser.marginVerticalPx,
    askUserCardMaxWidthPx: spec.rows.askUser.cardMaxWidthPx,
    askUserCardMinWidthPx: spec.rows.askUser.cardMinWidthPx,
    askUserCardPaddingPx: spec.rows.askUser.cardPaddingPx,
    askUserCardGapPx: spec.rows.askUser.cardGapPx,
    askUserTabsHeightPx: spec.rows.askUser.tabsHeightPx,
    askUserPanelHeightPx: spec.rows.askUser.panelHeightPx,
    askUserStatusHeightPx: spec.rows.askUser.statusHeightPx,
    askUserActionsHeightPx: spec.rows.askUser.actionsHeightPx,
    askUserHintHeightPx: spec.rows.askUser.hintHeightPx,
    askUserShellHeightPx,
    thoughtPaddingInlinePx: spec.rows.thought.paddingInlinePx,
    thoughtPaddingBlockPx: spec.rows.thought.paddingBlockPx,
    thoughtFontFamily: spec.rows.thought.typography.fontFamily,
    thoughtFontSizePx: spec.rows.thought.typography.fontSizePx,
    thoughtLineHeightPx: spec.rows.thought.typography.lineHeightPx,
    toolSummaryPaddingInlinePx: spec.rows.tools.summary.paddingInlinePx,
    toolSummaryPaddingBlockPx: spec.rows.tools.summary.paddingBlockPx,
    toolSummaryFontFamily: spec.rows.tools.summary.typography.fontFamily,
    toolSummaryFontSizePx: spec.rows.tools.summary.typography.fontSizePx,
    toolSummaryLineHeightPx: spec.rows.tools.summary.typography.lineHeightPx,
    toolSeparatorPaddingInlinePx: spec.rows.tools.summary.separatorPaddingInlinePx,
    toolStatusDotPaddingInlinePx: spec.rows.tools.summary.statusDotPaddingInlinePx,
    toolLoadingFontFamily: spec.rows.tools.loading.typography.fontFamily,
    toolLoadingFontSizePx: spec.rows.tools.loading.typography.fontSizePx,
    toolLoadingLineHeightPx: spec.rows.tools.loading.typography.lineHeightPx,
    toolItemGapPx: spec.rows.tools.itemGapPx,
    toolGroupGapPx: spec.rows.tools.groupGapPx,
    toolThoughtTitleFontFamily: spec.rows.tools.thoughtTitle.typography.fontFamily,
    toolThoughtTitleFontSizePx: spec.rows.tools.thoughtTitle.typography.fontSizePx,
    toolThoughtTitleLineHeightPx: spec.rows.tools.thoughtTitle.typography.lineHeightPx,
    toolThoughtTitleMarginBottomPx: spec.rows.tools.thoughtTitle.marginBottomPx,
    toolThoughtBodyPaddingPx: spec.rows.tools.thoughtBody.paddingPx,
    toolThoughtBodyBorderWidthPx: spec.rows.tools.thoughtBody.borderWidthPx,
    toolThoughtBodyFontFamily: spec.rows.tools.thoughtBody.typography.fontFamily,
    toolThoughtBodyFontSizePx: spec.rows.tools.thoughtBody.typography.fontSizePx,
    toolThoughtBodyLineHeightPx: spec.rows.tools.thoughtBody.typography.lineHeightPx,
  } as const;

  const layoutStyle = {
    "--wb-thread-max-width": `${layout.rowMaxWidthPx}px`,
    "--wb-session-padding-inline": `${layout.horizontalInsetPx}px`,
    "--wb-transcript-max-width": `${layout.rowMaxWidthPx}px`,
    "--wb-thread-indent-left": `${layout.indentLeftPx}px`,
    "--wb-markdown-body-font-size": `${layout.markdownBodyFontSizePx}px`,
    "--wb-markdown-body-line-height": `${layout.markdownBodyLineHeightPx}px`,
    "--wb-markdown-body-font-family": layout.markdownBodyFontFamily,
    "--wb-markdown-heading-1-font-size": `${layout.markdownHeadingFontSizePxByDepth[1]}px`,
    "--wb-markdown-heading-2-font-size": `${layout.markdownHeadingFontSizePxByDepth[2]}px`,
    "--wb-markdown-heading-3-font-size": `${layout.markdownHeadingFontSizePxByDepth[3]}px`,
    "--wb-markdown-heading-4-font-size": `${layout.markdownHeadingFontSizePxByDepth[4]}px`,
    "--wb-markdown-heading-1-line-height": `${layout.markdownHeadingLineHeightPxByDepth[1]}px`,
    "--wb-markdown-heading-2-line-height": `${layout.markdownHeadingLineHeightPxByDepth[2]}px`,
    "--wb-markdown-heading-3-line-height": `${layout.markdownHeadingLineHeightPxByDepth[3]}px`,
    "--wb-markdown-heading-4-line-height": `${layout.markdownHeadingLineHeightPxByDepth[4]}px`,
    "--wb-markdown-heading-font-weight": String(layout.markdownFontWeight.heading),
    "--wb-markdown-table-header-font-weight": String(layout.markdownFontWeight.tableHeader),
    "--wb-markdown-block-margin-bottom": `${layout.markdownBlockMarginBottomPx}px`,
    "--wb-markdown-heading-margin-top": `${layout.markdownHeadingMarginTopPx}px`,
    "--wb-markdown-heading-margin-bottom": `${layout.markdownHeadingMarginBottomPx}px`,
    "--wb-markdown-list-indent": `${layout.markdownListIndentPx}px`,
    "--wb-markdown-list-gap": `${layout.markdownListGapPx}px`,
    "--wb-markdown-list-marker-min-width": `${layout.markdownListMarkerMinWidthPx}px`,
    "--wb-markdown-list-marker-gap": `${layout.markdownListMarkerGapPx}px`,
    "--wb-markdown-inline-code-padding-block": `${layout.markdownInlineCodePaddingBlockPx}px`,
    "--wb-markdown-inline-code-padding-inline": `${layout.markdownInlineCodePaddingInlinePx}px`,
    "--wb-markdown-inline-code-border-width": `${layout.markdownInlineCodeBorderWidthPx}px`,
    "--wb-markdown-inline-code-border-radius": `${layout.markdownInlineCodeBorderRadiusPx}px`,
    "--wb-markdown-inline-code-font-size": `${layout.markdownInlineCodeFontSizePx}px`,
    "--wb-markdown-inline-code-font-family": layout.markdownInlineCodeFontFamily,
    "--wb-markdown-code-block-font-size": `${layout.markdownCodeBlockFontSizePx}px`,
    "--wb-markdown-code-block-line-height": `${layout.markdownCodeBlockLineHeightPx}px`,
    "--wb-markdown-blockquote-border-width": `${layout.markdownBlockquoteBorderWidthPx}px`,
    "--wb-markdown-blockquote-padding-inline-start": `${layout.markdownBlockquotePaddingInlineStartPx}px`,
    "--wb-markdown-image-width": `${layout.markdownImageWidthPx}px`,
    "--wb-markdown-image-height": `${layout.markdownImageHeightPx}px`,
    "--wb-markdown-table-border-width": `${layout.markdownTableBorderWidthPx}px`,
    "--wb-markdown-table-cell-padding-block": `${layout.markdownTableCellPaddingBlockPx}px`,
    "--wb-markdown-table-cell-padding-inline": `${layout.markdownTableCellPaddingInlinePx}px`,
    "--wb-message-row-padding-block": `${layout.messageRowPaddingBlockPx}px`,
    "--wb-message-bubble-padding-block": `${layout.messageBubblePaddingBlockPx}px`,
    "--wb-message-bubble-padding-inline": `${layout.messageBubblePaddingInlinePx}px`,
    "--wb-message-bubble-border-width": `${layout.messageBubbleBorderWidthPx}px`,
    "--wb-message-max-width": `${layout.messageMaxWidthRatio * 100}%`,
    "--wb-message-role-font-size": `${layout.messageRoleFontSizePx}px`,
    "--wb-message-role-line-height": `${layout.messageRoleLineHeightPx}px`,
    "--wb-message-toggle-margin-top": `${layout.messageToggleMarginTopPx}px`,
    "--wb-message-toggle-font-size": `${layout.messageToggleFontSizePx}px`,
    "--wb-message-toggle-line-height": `${layout.messageToggleLineHeightPx}px`,
    "--wb-message-attachment-width": `${layout.messageAttachmentWidthPx}px`,
    "--wb-message-attachment-height": `${layout.messageAttachmentHeightPx}px`,
    "--wb-message-attachment-gap": `${layout.messageAttachmentGapPx}px`,
    "--wb-message-attachment-margin-top": `${layout.messageAttachmentMarginTopPx}px`,
    "--wb-turn-header-bubble-padding-block": `${layout.turnHeaderBubblePaddingBlockPx}px`,
    "--wb-turn-header-bubble-padding-inline": `${layout.turnHeaderBubblePaddingInlinePx}px`,
    "--wb-turn-header-bubble-border-width": `${layout.turnHeaderBubbleBorderWidthPx}px`,
    "--wb-turn-header-copy-gutter": `${layout.turnHeaderCopyGutterPx}px`,
    "--wb-turn-header-collapsed-max-height": `${layout.turnHeaderCollapsedMaxHeightPx}px`,
    "--wb-askq-shell-height": `${layout.askUserShellHeightPx}px`,
    "--wb-askq-card-gap": `${layout.askUserCardGapPx}px`,
    "--wb-askq-tabs-height": `${layout.askUserTabsHeightPx}px`,
    "--wb-askq-panel-height": `${layout.askUserPanelHeightPx}px`,
    "--wb-askq-status-height": `${layout.askUserStatusHeightPx}px`,
    "--wb-askq-actions-height": `${layout.askUserActionsHeightPx}px`,
    "--wb-askq-hint-height": `${layout.askUserHintHeightPx}px`,
    "--wb-thought-row-padding-inline": `${layout.thoughtPaddingInlinePx}px`,
    "--wb-thought-row-padding-block": `${layout.thoughtPaddingBlockPx}px`,
    "--wb-thought-row-font-family": layout.thoughtFontFamily,
    "--wb-thought-row-font-size": `${layout.thoughtFontSizePx}px`,
    "--wb-thought-row-line-height": `${layout.thoughtLineHeightPx}px`,
    "--wb-tool-summary-padding-inline": `${layout.toolSummaryPaddingInlinePx}px`,
    "--wb-tool-summary-padding-block": `${layout.toolSummaryPaddingBlockPx}px`,
    "--wb-tool-summary-font-family": layout.toolSummaryFontFamily,
    "--wb-tool-summary-font-size": `${layout.toolSummaryFontSizePx}px`,
    "--wb-tool-summary-line-height": `${layout.toolSummaryLineHeightPx}px`,
    "--wb-tool-separator-padding-inline": `${layout.toolSeparatorPaddingInlinePx}px`,
    "--wb-tool-status-dot-padding-inline": `${layout.toolStatusDotPaddingInlinePx}px`,
    "--wb-tool-loading-font-family": layout.toolLoadingFontFamily,
    "--wb-tool-loading-font-size": `${layout.toolLoadingFontSizePx}px`,
    "--wb-tool-loading-line-height": `${layout.toolLoadingLineHeightPx}px`,
    "--wb-tool-item-gap": `${layout.toolItemGapPx}px`,
    "--wb-tool-group-gap": `${layout.toolGroupGapPx}px`,
    "--wb-tool-thought-title-font-family": layout.toolThoughtTitleFontFamily,
    "--wb-tool-thought-title-font-size": `${layout.toolThoughtTitleFontSizePx}px`,
    "--wb-tool-thought-title-line-height": `${layout.toolThoughtTitleLineHeightPx}px`,
    "--wb-tool-thought-title-margin-bottom": `${layout.toolThoughtTitleMarginBottomPx}px`,
    "--wb-tool-thought-body-padding": `${layout.toolThoughtBodyPaddingPx}px`,
    "--wb-tool-thought-body-border-width": `${layout.toolThoughtBodyBorderWidthPx}px`,
    "--wb-tool-thought-body-font-family": layout.toolThoughtBodyFontFamily,
    "--wb-tool-thought-body-font-size": `${layout.toolThoughtBodyFontSizePx}px`,
    "--wb-tool-thought-body-line-height": `${layout.toolThoughtBodyLineHeightPx}px`,
  } as CSSProperties;

  return {
    geometryRevision,
    measurementContract,
    rowMeasurementContract,
    layout,
    layoutStyle,
  };
}

export const SESSION_THREAD_GEOMETRY_VIEWS = buildSessionThreadGeometryViews();
