"""Synthetic Cargo.lock construction for release SBOM tests."""

from __future__ import annotations

import hashlib

SOURCE = "registry+https://github.com/rust-lang/crates.io-index"
SYNTHETIC_WORKSPACE_VERSION = "0.26.0"


def package(
    name: str,
    version: str,
    dependencies: tuple[str, ...] = (),
    external: bool = False,
) -> str:
    lines = ["[[package]]", f'name = "{name}"', f'version = "{version}"']
    if external:
        lines.extend(
            (
                f'source = "{SOURCE}"',
                f'checksum = "{hashlib.sha256(f"{name}-{version}".encode()).hexdigest()}"',
            )
        )
    if dependencies:
        lines.append("dependencies = [")
        lines.extend(f' "{dependency}",' for dependency in dependencies)
        lines.append("]")
    return "\n".join(lines)


def synthetic_lock_text() -> str:
    packages = [
        package(
            "ctx",
            "0.26.0",
            (
                "ctx-agent-application",
                "ctx-agent-integrations",
                "ctx-companion-bridge",
                "ctx-cli-presentation 1.0.0",
                "ctx-client-observability",
                "ctx-daemon-cli 1.0.0",
                "ctx-history-cli 1.0.0",
                "ctx-history-core",
                "ctx-history-refresh",
                "ctx-history-capture",
                "ctx-history-capture-model",
                "ctx-history-index",
                "ctx-history-jsonl",
                "ctx-history-provider-docproj",
                "ctx-history-source-io",
                "ctx-history-provider-gemini",
                "ctx-history-provider-native-jsonl",
                "ctx-history-provider-codex",
                "ctx-history-provider-claude-cursor",
                "ctx-history-provider-runtime",
                "ctx-history-providers-jsonl-shared",
                "ctx-history-providers-task-docs",
                "ctx-history-provider-mistral-mux",
                "ctx-history-providers-sqlite-selected",
                "ctx-history-providers-sqlite-inventory",
                "ctx-history-providers-sqlite-logical",
                "ctx-history-refresh-execution",
                "ctx-history-read-application",
                "ctx-terminal 1.0.0",
                "ctx-upgrade-engine",
            ),
        ),
        package(
            "ctx-agent-application",
            "0.26.0",
            ("ctx-agent-integrations", "ctx-client-observability"),
        ),
        package(
            "ctx-agent-integrations",
            "0.26.0",
            ("ctx-history-core",),
        ),
        package(
            "ctx-companion-bridge",
            "0.26.0",
            ("ctx-history-platform",),
        ),
        package(
            "ctx-cli-presentation",
            "1.0.0",
            (
                "ctx-agent-application",
                "ctx-agent-integrations",
                "ctx-client-observability",
                "ctx-history-cli 1.0.0",
                "ctx-history-core",
                "ctx-history-read-application",
                "ctx-history-refresh",
                "ctx-terminal 1.0.0",
                "ctx-upgrade-engine",
            ),
        ),
        package(
            "ctx-client-observability",
            "0.26.0",
            ("ctx-history-core",),
        ),
        package(
            "ctx-daemon-application",
            "1.0.0",
            (
                "ctx-client-observability",
                "ctx-daemon-runtime 1.0.0",
                "ctx-daemon-service 1.0.0",
                "ctx-history-core",
            ),
        ),
        package(
            "ctx-daemon-cli",
            "1.0.0",
            (
                "ctx-client-observability",
                "ctx-daemon-application 1.0.0",
                "ctx-daemon-runtime 1.0.0",
                "ctx-daemon-service 1.0.0",
                "ctx-history-core",
                "ctx-history-index",
                "ctx-history-read-application",
                "ctx-semantic-index",
                "ctx-semantic-model",
                "ctx-terminal 1.0.0",
                "ctx-upgrade-engine",
            ),
        ),
        package("ctx-history-core", "0.26.0"),
        package("ctx-history-platform", "0.26.0"),
        package(
            "ctx-history-capture",
            "0.26.0",
            (
                "ctx-history-capture-composition",
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-jsonl",
                "ctx-history-provider-claude-cursor",
                "ctx-history-provider-runtime",
            ),
        ),
        package(
            "ctx-history-capture-composition",
            "0.26.0",
            (
                "chrono 0.4.0",
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-index",
                "ctx-history-jsonl",
                "ctx-history-provider-claude-cursor",
                "ctx-history-provider-codex",
                "ctx-history-provider-docproj",
                "ctx-history-provider-fx",
                "ctx-history-provider-gemini",
                "ctx-history-provider-hermes",
                "ctx-history-provider-mistral-mux",
                "ctx-history-provider-native-jsonl",
                "ctx-history-provider-openclaw-sqlite",
                "ctx-history-provider-runtime",
                "ctx-history-providers-jsonl-shared",
                "ctx-history-providers-sqlite-inventory",
                "ctx-history-providers-sqlite-logical",
                "ctx-history-providers-sqlite-selected",
                "ctx-history-providers-task-docs",
                "ctx-history-source-discovery",
                "ctx-history-source-io",
                "serde_json 1.0.0",
                "sha2 0.10.9",
                "tempfile 3.0.0",
                "thiserror 1.0.0",
                "uuid 1.0.0",
            ),
        ),
        package(
            "ctx-history-provider-codex",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-provider-runtime",
                "ctx-history-source-io",
                "chrono 0.4.0",
                "serde_json 1.0.0",
                "sha2 0.10.9",
                "tempfile 3.0.0",
                "thiserror 1.0.0",
                "uuid 1.0.0",
            ),
        ),
        package(
            "ctx-history-cli",
            "1.0.0",
            (
                "ctx-client-observability",
                "ctx-daemon-cli 1.0.0",
                "ctx-history-core",
                "ctx-history-index",
                "ctx-history-read-application",
                "ctx-history-refresh",
                "ctx-terminal 1.0.0",
            ),
        ),
        package(
            "ctx-history-capture-model",
            "0.26.0",
            ("ctx-history-core", "serde_json 1.0.0"),
        ),
        package(
            "ctx-history-capture-runtime",
            "0.26.0",
            ("ctx-history-capture-model", "ctx-history-core", "uuid 1.0.0"),
        ),
        package(
            "ctx-daemon-runtime",
            "1.0.0",
            ("ctx-history-core",),
        ),
        package(
            "ctx-daemon-service",
            "1.0.0",
            (
                "ctx-client-observability",
                "ctx-daemon-runtime 1.0.0",
                "ctx-history-core",
                "ctx-history-index",
                "ctx-semantic-index",
                "ctx-semantic-model",
                "ctx-upgrade-engine",
            ),
        ),
        package(
            "ctx-history-index",
            "0.26.0",
            (
                "ctx-history-index-format",
                "ctx-history-index-query",
                "ctx-semantic-model",
                "tantivy 0.26.1",
            ),
        ),
        package(
            "ctx-history-index-format",
            "0.26.0",
            ("ctx-history-core", "tantivy 0.26.1"),
        ),
        package(
            "ctx-history-index-query",
            "0.26.0",
            (
                "ctx-history-core",
                "ctx-history-index-format",
                "tantivy 0.26.1",
            ),
        ),
        package(
            "ctx-history-jsonl",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "serde_json 1.0.0",
            ),
        ),
        package(
            "ctx-history-provider-claude-cursor",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-jsonl",
                "ctx-history-provider-runtime",
            ),
        ),
        package(
            "ctx-history-provider-docproj",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-provider-runtime",
                "ctx-history-source-discovery",
                "ctx-history-source-io",
                "ctx-history-source-sqlite",
                "chrono 0.4.0",
                "rusqlite 0.32.1",
                "serde 1.0.0",
                "serde_json 1.0.0",
                "sha2 0.10.9",
                "thiserror 1.0.0",
            ),
        ),
        package(
            "ctx-history-provider-fx",
            SYNTHETIC_WORKSPACE_VERSION,
            (
                "base64 0.22.0",
                "chrono 0.4.0",
                "ctx-history-core",
                "ctx-history-jsonl",
                "ctx-history-provider-runtime",
                "serde 1.0.0",
                "serde_json 1.0.0",
                "sha2 0.10.9",
                "tempfile 3.0.0",
                "thiserror 1.0.0",
            ),
        ),
        package(
            "ctx-history-provider-gemini",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-core",
                "ctx-history-jsonl",
                "ctx-history-source-io",
                "chrono 0.4.0",
                "serde 1.0.0",
                "serde_json 1.0.0",
                "sha2 0.10.9",
                "thiserror 1.0.0",
            ),
        ),
        package(
            "ctx-history-provider-hermes",
            SYNTHETIC_WORKSPACE_VERSION,
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-provider-runtime",
                "ctx-history-source-io",
                "ctx-history-source-sqlite",
                "chrono 0.4.0",
                "rusqlite 0.32.1",
                "serde 1.0.0",
                "serde_json 1.0.0",
                "sha2 0.10.9",
                "tempfile 3.0.0",
                "thiserror 1.0.0",
            ),
        ),
        package(
            "ctx-history-provider-mistral-mux",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-jsonl",
                "ctx-history-provider-runtime",
                "ctx-history-source-io",
                "chrono 0.4.0",
                "serde 1.0.0",
                "serde_json 1.0.0",
                "sha2 0.10.9",
            ),
        ),
        package(
            "ctx-history-provider-native-jsonl",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-jsonl",
                "serde_json 1.0.0",
            ),
        ),
        package(
            "ctx-history-provider-openclaw-sqlite",
            "0.26.0",
            (
                "chrono 0.4.0",
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-openclaw-schema",
                "ctx-history-provider-runtime",
                "ctx-history-providers-jsonl-shared",
                "rusqlite 0.32.1",
                "serde_json 1.0.0",
                "sha2 0.10.9",
                "tempfile 3.0.0",
                "thiserror 1.0.0",
                "zstd 0.13.0",
            ),
        ),
        package(
            "ctx-history-openclaw-schema",
            "0.26.0",
            ("rusqlite 0.32.1", "thiserror 1.0.0"),
        ),
        package(
            "ctx-history-provider-runtime",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-jsonl",
            ),
        ),
        package(
            "ctx-history-providers-task-docs",
            "0.26.0",
            (
                "base64 0.22.0",
                "chrono 0.4.0",
                "libc 0.2.0",
                "regex 1.0.0",
                "serde 1.0.0",
                "serde_json 1.0.0",
                "sha2 0.10.9",
                "thiserror 1.0.0",
                "uuid 1.0.0",
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-source-io",
            ),
        ),
        package(
            "ctx-history-source-io",
            "0.26.0",
        ),
        package(
            "ctx-history-source-discovery",
            "0.26.0",
            ("ctx-history-openclaw-schema",),
        ),
        package(
            "ctx-history-source-sqlite",
            "0.26.0",
            ("ctx-history-source-io",),
        ),
        package(
            "ctx-history-providers-jsonl-shared",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-jsonl",
                "ctx-history-provider-runtime",
            ),
        ),
        package(
            "ctx-history-providers-sqlite-selected",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-source-io",
                "ctx-history-source-sqlite",
            ),
        ),
        package(
            "ctx-history-providers-sqlite-inventory",
            SYNTHETIC_WORKSPACE_VERSION,
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-provider-runtime",
                "ctx-history-source-io",
                "ctx-history-source-sqlite",
            ),
        ),
        package(
            "ctx-history-providers-sqlite-logical",
            "0.26.0",
            (
                "ctx-history-capture-model",
                "ctx-history-capture-runtime",
                "ctx-history-core",
                "ctx-history-source-io",
                "ctx-history-source-sqlite",
                "rmpv 1.0.0",
                "serde_json 1.0.0",
            ),
        ),
        package(
            "ctx-history-refresh-execution",
            "0.26.0",
            ("ctx-history-capture-runtime", "ctx-history-provider-runtime"),
        ),
        package(
            "ctx-history-refresh",
            "0.26.0",
            (
                "ctx-history-core",
                "ctx-history-index",
                "ctx-history-refresh-execution",
            ),
        ),
        package(
            "ctx-history-read-application",
            "0.26.0",
            (
                "ctx-history-core",
                "ctx-history-index-format",
                "ctx-history-index-query",
            ),
        ),
        package(
            "ctx-managed-pair-engine",
            "0.26.0",
            ("ctx-history-platform",),
        ),
        package(
            "ctx-semantic-index",
            "0.26.0",
            (
                "ctx-history-core",
                "ctx-history-index",
                "ctx-semantic-model",
                "memmap2 0.9.0",
            ),
        ),
        package(
            "ctx-semantic-model",
            "0.26.0",
            ("ctx-history-core",),
        ),
        package("ctx-terminal", "1.0.0"),
        package(
            "ctx-upgrade-engine",
            "0.26.0",
            ("ctx-history-core", "ctx-managed-pair-engine"),
        ),
        package("chrono", "0.4.0", external=True),
        package("base64", "0.22.0", external=True),
        package("fs4", "0.1.0", external=True),
        package("libc", "0.2.0", external=True),
        package("lz4_flex", "0.11.0", external=True),
        package("memmap2", "0.9.0", external=True),
        package("rmpv", "1.0.0", external=True),
        package("regex", "1.0.0", external=True),
        package("rusqlite", "0.32.1", external=True),
        package("serde", "1.0.0", external=True),
        package("sha2", "0.10.9", external=True),
        package("serde_json", "1.0.0", external=True),
        package(
            "tantivy",
            "0.26.1",
            (
                "fs4 0.1.0",
                "lz4_flex 0.11.0",
                "memmap2 0.9.0",
                "tempfile 3.0.0",
                "zstd 0.13.0",
            ),
            external=True,
        ),
        package("tempfile", "3.0.0", external=True),
        package("thiserror", "1.0.0", external=True),
        package("uuid", "1.0.0", external=True),
        package("zstd", "0.13.0", external=True),
    ]
    return "version = 4\n\n" + "\n\n".join(packages) + "\n"
