use super::*;

pub(super) fn workspace_provider_and_config_routes() -> axum::Router<RouteState> {
    axum::Router::new()
        .route(
            "/api/workspaces/:id/providers/:provider_id/options",
            get(provider_launch::get_provider_options),
        )
        .route(
            "/api/workspaces/:id/providers/bootstrap",
            get(get_workspace_providers_bootstrap),
        )
        .route(
            "/api/workspaces/:id/providers/:provider_id/authenticate",
            post(provider_launch::authenticate_provider_for_workspace),
        )
        .route(
            "/api/workspaces/:id/providers/:provider_id/verify",
            post(provider_launch::verify_provider_for_workspace),
        )
        .route(
            "/api/workspaces/:id/attachments",
            get(list_workspace_attachments)
                .post(create_workspace_attachment)
                .delete(delete_workspace_attachment),
        )
        .route(
            "/api/workspaces/:id/attachments/sync",
            post(sync_workspace_attachments),
        )
        .route(
            "/api/workspaces/:id/agent_system_prompt",
            get(get_agent_system_prompt).post(update_agent_system_prompt),
        )
        .route(
            "/api/workspaces/:id/subagent_system_prompt",
            get(get_subagent_system_prompt).post(update_subagent_system_prompt),
        )
        .route(
            "/api/workspaces/:id/provider_model_preferences/:provider_id",
            get(get_workspace_provider_model_preference)
                .post(update_workspace_provider_model_preference),
        )
        .route(
            "/api/workspaces/:id/primary_branch",
            get(get_workspace_primary_branch).post(update_workspace_primary_branch),
        )
        .route(
            "/api/workspaces/:id/merge_queue_config",
            get(get_merge_queue_config).post(update_merge_queue_config),
        )
        .route(
            "/api/workspaces/:id/execution_config",
            get(get_execution_config).post(update_execution_config),
        )
        .route(
            "/api/workspaces/:id/worktree_bootstrap_config",
            get(get_worktree_bootstrap_config).post(update_worktree_bootstrap_config),
        )
}
