#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(super) struct GooseNativeMetrics {
    pub(super) snapshot_attempts: u64,
    pub(super) identity_prescan_queries: u64,
    pub(super) session_page_queries: u64,
    pub(super) message_page_queries: u64,
    pub(super) native_sessions: u64,
    pub(super) native_messages: u64,
    pub(super) retained_events: u64,
    pub(super) excluded_outputs: u64,
    pub(super) excluded_output_bytes_observed: u64,
    pub(super) outputs_success: u64,
    pub(super) outputs_failure: u64,
    pub(super) outputs_timeout: u64,
    pub(super) outputs_unknown: u64,
    pub(super) rejected_records: u64,
    pub(super) retained_content_cells_transferred: u64,
    pub(super) retained_content_bytes_transferred: u64,
    // These stay explicit so output-heavy tests can prove that no output
    // material crossed the SQLite/Rust boundary or reached derived surfaces.
    pub(super) output_content_cells_transferred: u64,
    pub(super) output_content_bytes_transferred: u64,
    pub(super) output_hashes_built: u64,
    pub(super) output_previews_built: u64,
    pub(super) output_touches_built: u64,
    pub(super) output_fts_documents_built: u64,
    pub(super) output_handoffs_built: u64,
    pub(super) generic_output_dtos_built: u64,
    pub(super) pro_output_pages: u64,
    pub(super) pro_output_rejections: u64,
}
