load("//tools/bazel:gates.bzl", "loc_check_inputs")

loc_check_inputs(name = "loc_check_inputs")

exports_files(
    [
        "ort-freebsd-release-env-order.patch",
        "rules-rust-freebsd-host.patch",
        "rules-rust-windows-cargo-runfiles.patch",
        "rules-rust-windows-gnu-dlltool-path.patch",
    ],
    visibility = ["//visibility:public"],
)
