pub(crate) mod blame;
pub(crate) mod doctor;
pub(crate) mod import;
pub(crate) mod index;
mod index_dashboard;
pub(crate) mod list;
pub(crate) mod locate;
pub(crate) mod mcp_tool_call;
pub(crate) mod search;
pub(crate) mod setup;
pub(crate) mod show;
pub(crate) mod source_index;
pub(crate) mod sources;
pub(crate) mod stats;
pub(crate) mod status;
