#[allow(unused_imports)]
use super::*;

text_enum! {
    pub enum CaptureProvider {
        Codex => "codex",
        Claude => "claude",
        Pi => "pi",
        OpenCode => "opencode",
        Kilo => "kilo",
        KiroCli => "kiro_cli",
        Antigravity => "antigravity",
        Gemini => "gemini",
        Tabnine => "tabnine",
        Cursor => "cursor",
        Windsurf => "windsurf",
        Zed => "zed",
        CopilotCli => "copilot_cli",
        FactoryAiDroid => "factory_ai_droid",
        QwenCode => "qwen_code",
        KimiCodeCli => "kimi_code_cli",
        Auggie => "auggie",
        Junie => "junie",
        Firebender => "firebender",
        ForgeCode => "forgecode",
        DeepAgents => "deepagents",
        MistralVibe => "mistral_vibe",
        Mux => "mux",
        RovoDev => "rovodev",
        OpenClaw => "openclaw",
        Hermes => "hermes",
        NanoClaw => "nanoclaw",
        AstrBot => "astrbot",
        Shelley => "shelley",
        Continue => "continue",
        OpenHands => "openhands",
        Cline => "cline",
        RooCode => "roo_code",
        Crush => "crush",
        Goose => "goose",
        Lingma => "lingma",
        Qoder => "qoder",
        Warp => "warp",
        CodeBuddy => "codebuddy",
        Trae => "trae",
        Shell => "shell",
        Git => "git",
        Jj => "jj",
        Gh => "gh",
        Custom => "custom",
        Unknown => "unknown",
    }
    default Unknown
}
